### ISSUE TITLE
relative URLs

### ISSUE THREAD

**Issue by olegatro** [tgalopin/html-sanitizer#28]
> Note: the Sanitizer does not allow relative URLs: they are always filtered out for security reasons.

Any chance to disable this setting ?

**Comment by olegatro** [comment]
Hi @alartigue, created temporary solution if you need

https://github.com/olegatro/html-sanitizer_local_uri

**Comment by tgalopin** [comment]
Hello @olegatro and @alartigue!

I think this could be a setting inside the A and Image extensions, something like `'allow_relative_links' => false`. However, note that detecting a relative path is much more difficult than detecting a URL, which is why I didn't implement it to avoid security issues in the future.

If you are interested in providing a PR for this, I would be glad to give you a hand :) .

**Comment by alartigue** [comment]
Hello,
I've implemented @olegatro extension and it worked like a charm. Thanks a lot!
@tgalopin , I'm not a security expert, I don't think I'm capable of writting this piece of code :(

**Comment by tgalopin** [comment]
@olegatro if you have a few minutes to create a Composer package for your work, it could be a nice way to let @alartigue use the feature easily perhaps :) ?

I'm glad you found a good solution for this!

**Comment by olegatro** [comment]
Hi @tgalopin , I will try send PR in the nearest future.

Will it be right solution to check `allow_relative_links` setting [here](https://github.com/tgalopin/html-sanitizer/blob/master/src/Extension/Basic/NodeVisitor/ANodeVisitor.php#L69) (before `setAttribute`) ?

**Comment by voltel** [comment]
@tgalopin @olegatro I'd really be interested in seeing this effort resolved with a new config feature. I try to use sanitizer with my Symfony project, and having a config option `allow_relative_links` would be the best outcome for me. 

For those wondering about integration of fix by @olegatro (Thanks!), I made the following configurations in my Symfony 5 project to adopt the solution:

1. Downloaded and copied the Sanitizer directory ([see the GitHub page](https://github.com/olegatro/html-sanitizer_local_uri)) to my `src` project directory. 

2. Added this line to the composer.json (tells autoloader where to look for `Sanitizer` namespace):
```json
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "Sanitizer\\": "src/Sanitizer/"
        }
    },
```

3. Added these definitions to my `services.yaml`:
```yaml
    # Read at: https://github.com/tgalopin/html-sanitizer-bundle#registering-an-extension
    Sanitizer\Extension\A\AExtension:
        tags: [{ name: 'html_sanitizer.extension' }]

    # Read at: https://github.com/tgalopin/html-sanitizer-bundle#registering-an-extension
    Sanitizer\Extension\Image\ImageExtension:
        tags: [{ name: 'html_sanitizer.extension' }]
```

4. In `config/packages/html_sanitizer.yaml` changed config in this way:
```yaml
html_sanitizer:
    default_sanitizer: 'default'
    sanitizers:
        default:
            # Read https://github.com/tgalopin/html-sanitizer/blob/master/docs/1-getting-started.md#extensions
            # to learn more about which extensions you would like to enable.
            extensions:
                - 'basic'
                - 'list'
                - 'table'
                #- 'image'
                # - 'code'
                # - 'iframe'
                - 'extra'
                # https://github.com/tgalopin/html-sanitizer-bundle#registering-an-extension
                # https://github.com/olegatro/html-sanitizer_local_uri
                # See classes in src/Sanitizer/Extension directory
                - 'custom-a'
                - 'custom-image'
```
